import { mutation,query } from "./_generated/server";import { v } from "convex/values";import { requireAdmin } from "./lib/auth";
export const activate=mutation({args:{ownerId:v.id("users"),packageName:v.string(),expiresAt:v.number()},handler:async(ctx,args)=>{const admin=await requireAdmin(ctx),existing=await ctx.db.query("subscriptions").withIndex("owner",q=>q.eq("ownerId",args.ownerId)).unique();if(existing)await ctx.db.patch(existing._id,{status:"active",packageName:args.packageName,startsAt:Date.now(),expiresAt:args.expiresAt});else await ctx.db.insert("subscriptions",{ownerId:args.ownerId,status:"active",trialLimit:10,packageName:args.packageName,startsAt:Date.now(),expiresAt:args.expiresAt});await ctx.db.insert("auditLogs",{actorId:admin._id,action:"subscription.activate",targetType:"user",targetId:args.ownerId,metadata:{packageName:args.packageName},timestamp:Date.now()})}});
export const users=query({args:{},handler:async ctx=>{await requireAdmin(ctx);const users=await ctx.db.query("users").collect();return Promise.all(users.map(async user=>{const portals=await ctx.db.query("portals").withIndex("owner",q=>q.eq("ownerId",user._id)).collect();const subscription=await ctx.db.query("subscriptions").withIndex("owner",q=>q.eq("ownerId",user._id)).unique();return {user,portalCount:portals.length,responseCount:portals.reduce((sum,p)=>sum+p.submissionCount,0),subscription}}))}});
export const setState=mutation({args:{userId:v.id("users"),state:v.union(v.literal("active"),v.literal("suspended"))},handler:async(ctx,args)=>{const admin=await requireAdmin(ctx);if(admin._id===args.userId&&args.state==="suspended")throw new Error("You cannot suspend your own account");await ctx.db.patch(args.userId,{state:args.state});await ctx.db.insert("auditLogs",{actorId:admin._id,action:`user.${args.state}`,targetType:"user",targetId:args.userId,timestamp:Date.now()})}});

const localized=v.object({ka:v.string(),en:v.string(),ru:v.string()});
const clean=(value:string,max=240)=>value.normalize("NFC").trim().slice(0,max);
export const catalog=query({args:{},handler:async ctx=>{await requireAdmin(ctx);return {products:(await ctx.db.query("products").collect()).sort((a,b)=>a.sortOrder-b.sortOrder),packages:(await ctx.db.query("packages").collect()).sort((a,b)=>(a.sortOrder??0)-(b.sortOrder??0))};}});
export const initializeCatalog=mutation({args:{},handler:async ctx=>{
  const admin=await requireAdmin(ctx),products=await ctx.db.query("products").collect(),packages=await ctx.db.query("packages").collect();
  const productSlugs=new Set(products.map(item=>item.slug)),packageSlugs=new Set(packages.map(item=>item.slug));
  const defaultsProducts=[
    {slug:"nfc-stand",kind:"individual" as const,name:{ka:"NFC + QR სტენდი",en:"NFC + QR stand",ru:"NFC + QR стенд"},description:{ka:"მაგიდისთვის — სწრაფი შეხება ან სკანირება",en:"For counters — a quick tap or scan",ru:"Для стойки — касание или сканирование"},priceDisplay:"₾30",priceGel:30,compareAtPriceGel:49,stockQuantity:12,available:true,imageUrl:"/products/stand.jpeg",sortOrder:1},
    {slug:"nfc-card",kind:"individual" as const,name:{ka:"NFC ბარათი",en:"NFC card",ru:"NFC-карта"},description:{ka:"კომპაქტური ბარათი გუნდისთვის",en:"A compact card for your team",ru:"Компактная карта для вашей команды"},priceDisplay:"₾10",priceGel:10,compareAtPriceGel:19,stockQuantity:8,available:true,imageUrl:"/products/card.jpeg",sortOrder:2},
    {slug:"starter-set",kind:"set" as const,name:{ka:"საწყისი ნაკრები",en:"Starter bundle",ru:"Стартовый набор"},description:{ka:"სტენდი და ბარათი ერთ კომპლექტში",en:"A stand and card in one set",ru:"Стенд и карта в одном наборе"},priceDisplay:"₾35",priceGel:35,compareAtPriceGel:59,stockQuantity:0,available:true,imageUrl:"/products/bundle.png",sortOrder:3},
  ];
  const defaultsPackages=[
    {slug:"trial",name:{ka:"საცდელი",en:"Trial",ru:"Пробный"},description:{ka:"გამოსცადეთ უკუკავშირის სრული ციკლი.",en:"Try the complete feedback loop.",ru:"Попробуйте полный цикл обратной связи."},priceDisplay:"Free",priceGel:0,features:["10 responses","1 portal","QR link"],featuresLocalized:{ka:["10 პასუხი","1 პორტალი","QR ბმული"],en:["10 responses","1 portal","QR link"],ru:["10 ответов","1 портал","QR-ссылка"]},portalLimit:1,visible:true,sortOrder:1},
    {slug:"growth",name:{ka:"ზრდა",en:"Growth",ru:"Рост"},description:{ka:"ბიზნესებისთვის, რომლებიც მომსახურებას მუდმივად აუმჯობესებენ.",en:"For teams improving every customer experience.",ru:"Для команд, улучшающих каждый клиентский опыт."},priceDisplay:"₾49 / month",priceGel:49,features:["5 portals","Unlimited feedback","Analytics & inbox","Email alerts"],featuresLocalized:{ka:["5 პორტალი","ულიმიტო უკუკავშირი","ანალიტიკა და ინბოქსი","ელფოსტის შეტყობინებები"],en:["5 portals","Unlimited feedback","Analytics & inbox","Email alerts"],ru:["5 порталов","Безлимитные отзывы","Аналитика и входящие","Email-уведомления"]},portalLimit:5,visible:true,sortOrder:2},
    {slug:"business",name:{ka:"ბიზნესი",en:"Business",ru:"Бизнес"},description:{ka:"მოქნილი პირობები დიდი გუნდებისთვის.",en:"Flexible support for larger teams.",ru:"Гибкие условия для больших команд."},priceDisplay:"Custom",priceGel:0,features:["Everything in Growth","Priority onboarding","Flexible terms"],featuresLocalized:{ka:["Growth-ის ყველა ფუნქცია","პრიორიტეტული ჩართვა","მოქნილი პირობები"],en:["Everything in Growth","Priority onboarding","Flexible terms"],ru:["Всё из тарифа Рост","Приоритетный запуск","Гибкие условия"]},portalLimit:20,visible:true,sortOrder:3},
  ];
  let inserted=0;
  for(const item of defaultsProducts)if(!productSlugs.has(item.slug)){await ctx.db.insert("products",item);inserted++}
  for(const item of defaultsPackages)if(!packageSlugs.has(item.slug)){await ctx.db.insert("packages",item);inserted++}
  if(inserted)await ctx.db.insert("auditLogs",{actorId:admin._id,action:"catalog.initialize",targetType:"catalog",targetId:"defaults",metadata:{inserted},timestamp:Date.now()});
  return {inserted};
}});
export const saveProduct=mutation({args:{productId:v.optional(v.id("products")),slug:v.string(),kind:v.union(v.literal("individual"),v.literal("set")),name:localized,description:localized,priceGel:v.number(),compareAtPriceGel:v.optional(v.number()),stockQuantity:v.number(),available:v.boolean(),imageUrl:v.string(),sortOrder:v.number()},handler:async(ctx,args)=>{const admin=await requireAdmin(ctx),{productId,...values}=args,payload={...values,slug:clean(values.slug,80).toLowerCase(),name:{ka:clean(values.name.ka),en:clean(values.name.en),ru:clean(values.name.ru)},description:{ka:clean(values.description.ka,600),en:clean(values.description.en,600),ru:clean(values.description.ru,600)},imageUrl:clean(values.imageUrl,500),priceDisplay:`₾${Math.max(0,values.priceGel)}`,priceGel:Math.max(0,values.priceGel),compareAtPriceGel:values.compareAtPriceGel&&values.compareAtPriceGel>values.priceGel?values.compareAtPriceGel:undefined,stockQuantity:values.kind==="individual"?Math.max(0,Math.floor(values.stockQuantity)):0};const id=productId?(await ctx.db.patch(productId,payload),productId):await ctx.db.insert("products",payload);await ctx.db.insert("auditLogs",{actorId:admin._id,action:productId?"product.update":"product.create",targetType:"product",targetId:id,timestamp:Date.now()});return id}});
export const removeProduct=mutation({args:{productId:v.id("products")},handler:async(ctx,args)=>{const admin=await requireAdmin(ctx);await ctx.db.delete(args.productId);await ctx.db.insert("auditLogs",{actorId:admin._id,action:"product.delete",targetType:"product",targetId:args.productId,timestamp:Date.now()})}});
export const savePackage=mutation({args:{packageId:v.optional(v.id("packages")),slug:v.string(),name:localized,description:localized,priceGel:v.number(),compareAtPriceGel:v.optional(v.number()),featuresLocalized:v.object({ka:v.array(v.string()),en:v.array(v.string()),ru:v.array(v.string())}),portalLimit:v.number(),visible:v.boolean(),sortOrder:v.number()},handler:async(ctx,args)=>{const admin=await requireAdmin(ctx),{packageId,...values}=args,payload={...values,slug:clean(values.slug,80).toLowerCase(),name:{ka:clean(values.name.ka),en:clean(values.name.en),ru:clean(values.name.ru)},description:{ka:clean(values.description.ka,600),en:clean(values.description.en,600),ru:clean(values.description.ru,600)},featuresLocalized:{ka:values.featuresLocalized.ka.map(x=>clean(x)).filter(Boolean),en:values.featuresLocalized.en.map(x=>clean(x)).filter(Boolean),ru:values.featuresLocalized.ru.map(x=>clean(x)).filter(Boolean)},features:values.featuresLocalized.en.map(x=>clean(x)).filter(Boolean),priceDisplay:values.priceGel>0?`₾${values.priceGel} / month`:"Custom",priceGel:Math.max(0,values.priceGel),compareAtPriceGel:values.compareAtPriceGel&&values.compareAtPriceGel>values.priceGel?values.compareAtPriceGel:undefined,portalLimit:Math.max(1,Math.floor(values.portalLimit))};const id=packageId?(await ctx.db.patch(packageId,payload),packageId):await ctx.db.insert("packages",payload);await ctx.db.insert("auditLogs",{actorId:admin._id,action:packageId?"package.update":"package.create",targetType:"package",targetId:id,timestamp:Date.now()});return id}});
export const removePackage=mutation({args:{packageId:v.id("packages")},handler:async(ctx,args)=>{const admin=await requireAdmin(ctx);await ctx.db.delete(args.packageId);await ctx.db.insert("auditLogs",{actorId:admin._id,action:"package.delete",targetType:"package",targetId:args.packageId,timestamp:Date.now()})}});
