"use client";
import { useAuthActions } from "@convex-dev/auth/react";
import { Chrome } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import type { Locale } from "@/lib/i18n";

const authCopy={
  ka:{google:"Google-ით გაგრძელება",or:"ან ელფოსტით",email:"ელფოსტა",password:"პაროლი",confirm:"გაიმეორეთ პაროლი",login:"შესვლა",register:"რეგისტრაცია",newUser:"ანგარიში არ გაქვთ?",existing:"უკვე გაქვთ ანგარიში?",create:"შექმენით ანგარიში",back:"შესვლაზე დაბრუნება",mismatch:"პაროლები არ ემთხვევა",failed:"მონაცემები არასწორია ან ანგარიში უკვე არსებობს."},
  en:{google:"Continue with Google",or:"or use email",email:"Email",password:"Password",confirm:"Confirm password",login:"Sign in",register:"Register",newUser:"New to ReviewPortal?",existing:"Already have an account?",create:"Create an account",back:"Back to sign in",mismatch:"Passwords do not match",failed:"Those details are incorrect or the account already exists."},
  ru:{google:"Продолжить с Google",or:"или используйте почту",email:"Эл. почта",password:"Пароль",confirm:"Повторите пароль",login:"Войти",register:"Регистрация",newUser:"Впервые в ReviewPortal?",existing:"Уже есть аккаунт?",create:"Создать аккаунт",back:"Вернуться ко входу",mismatch:"Пароли не совпадают",failed:"Данные неверны или аккаунт уже существует."},
};

export function SignInForm({locale}:{locale:Locale}){const {signIn}=useAuthActions(),router=useRouter(),t=authCopy[locale];const [mode,setMode]=useState<"signIn"|"signUp">("signIn"),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),password=String(data.get("password")??"");if(mode==="signUp"&&password!==String(data.get("confirm")??"")){setError(t.mismatch);return}setBusy(true);setError("");try{await signIn("password",{email:String(data.get("email")??"").trim().toLowerCase(),password,flow:mode});router.push("/dashboard");router.refresh()}catch{setError(t.failed)}finally{setBusy(false)}}return <><button className="button google" onClick={()=>void signIn("google",{redirectTo:"/dashboard"})}><Chrome size={19}/>{t.google}</button><div className="auth-divider"><span>{t.or}</span></div><form className="credential-form" onSubmit={submit}><label>{t.email}<input required name="email" type="email" autoComplete="email"/></label><label>{t.password}<input required minLength={8} name="password" type="password" autoComplete={mode==="signUp"?"new-password":"current-password"}/></label>{mode==="signUp"?<label>{t.confirm}<input required minLength={8} name="confirm" type="password" autoComplete="new-password"/></label>:null}{error?<p role="alert" className="auth-error">{error}</p>:null}<button className="button" disabled={busy} type="submit">{busy?"…":mode==="signIn"?t.login:t.register}</button></form><p className="auth-switch">{mode==="signIn"?t.newUser:t.existing} <button type="button" onClick={()=>{setMode(mode==="signIn"?"signUp":"signIn");setError("")}}>{mode==="signIn"?t.create:t.back}</button></p></>}
export function AuthNotConfigured(){return <div><button className="button google" disabled><Chrome size={19}/>Continue with Google</button><p className="trial" style={{lineHeight:1.5}}>Google sign-in is ready for credentials. Follow <strong>docs/GOOGLE_OAUTH_SETUP.md</strong> after the production URL is created.</p></div>}
