export const products = [
  { slug:"nfc-stand",kind:"individual",image:"/products/stand.jpeg",name:{ka:"NFC + QR სტენდი",en:"NFC + QR stand",ru:"NFC + QR стенд"},detail:{ka:"მაგიდისთვის — სწრაფი შეხება ან სკანირება",en:"For counters — a quick tap or scan",ru:"Для стойки — касание или сканирование"},priceGel:30,compareAtPriceGel:49,stock:12,available:true,sortOrder:1 },
  { slug:"nfc-card",kind:"individual",image:"/products/card.jpeg",name:{ka:"NFC ბარათი",en:"NFC card",ru:"NFC-карта"},detail:{ka:"კომპაქტური ბარათი გუნდისთვის",en:"A compact card for your team",ru:"Компактная карта для вашей команды"},priceGel:10,compareAtPriceGel:19,stock:8,available:true,sortOrder:2 },
  { slug:"starter-set",kind:"set",image:"/products/bundle.png",name:{ka:"საწყისი ნაკრები",en:"Starter bundle",ru:"Стартовый набор"},detail:{ka:"სტენდი და ბარათი ერთ კომპლექტში",en:"A stand and card in one set",ru:"Стенд и карта в одном наборе"},priceGel:35,compareAtPriceGel:59,stock:0,available:true,sortOrder:3 },
] as const;

export const plans = [
  {slug:"trial",name:{ka:"საცდელი",en:"Trial",ru:"Пробный"},description:{ka:"გამოსცადეთ უკუკავშირის სრული ციკლი.",en:"Try the complete feedback loop.",ru:"Попробуйте полный цикл обратной связи."},priceGel:0,compareAtPriceGel:undefined,features:{ka:["10 პასუხი","1 პორტალი","QR ბმული"],en:["10 responses","1 portal","QR link"],ru:["10 ответов","1 портал","QR-ссылка"]},portalLimit:1,visible:true,sortOrder:1},
  {slug:"growth",name:{ka:"ზრდა",en:"Growth",ru:"Рост"},description:{ka:"ბიზნესებისთვის, რომლებიც მომსახურებას მუდმივად აუმჯობესებენ.",en:"For teams improving every customer experience.",ru:"Для команд, улучшающих каждый клиентский опыт."},priceGel:49,compareAtPriceGel:undefined,features:{ka:["5 პორტალი","ულიმიტო უკუკავშირი","ანალიტიკა და ინბოქსი","ელფოსტის შეტყობინებები"],en:["5 portals","Unlimited feedback","Analytics & inbox","Email alerts"],ru:["5 порталов","Безлимитные отзывы","Аналитика и входящие","Email-уведомления"]},portalLimit:5,visible:true,sortOrder:2},
  {slug:"business",name:{ka:"ბიზნესი",en:"Business",ru:"Бизнес"},description:{ka:"მოქნილი პირობები დიდი გუნდებისთვის.",en:"Flexible support for larger teams.",ru:"Гибкие условия для больших команд."},priceGel:0,compareAtPriceGel:undefined,features:{ka:["Growth-ის ყველა ფუნქცია","პრიორიტეტული ჩართვა","მოქნილი პირობები"],en:["Everything in Growth","Priority onboarding","Flexible terms"],ru:["Всё из тарифа Рост","Приоритетный запуск","Гибкие условия"]},portalLimit:20,visible:true,sortOrder:3},
] as const;

export const whatsapp = (message: string) => `https://wa.me/995577665525?text=${encodeURIComponent(message)}`;
