export const products = [
  { slug:"nfc-stand",kind:"individual",image:"/products/stand.jpeg",name:{ka:"NFC + QR სტენდი",en:"NFC + QR stand",ru:"NFC + QR стенд"},detail:{ka:"მაგიდისთვის — სწრაფი შეხება ან სკანირება",en:"For counters — a quick tap or scan",ru:"Для стойки — касание или сканирование"},priceGel:30,compareAtPriceGel:49,stock:12,available:true,sortOrder:1 },
  { slug:"nfc-card",kind:"individual",image:"/products/card.jpeg",name:{ka:"NFC ბარათი",en:"NFC card",ru:"NFC-карта"},detail:{ka:"კომპაქტური ბარათი გუნდისთვის",en:"A compact card for your team",ru:"Компактная карта для вашей команды"},priceGel:10,compareAtPriceGel:19,stock:8,available:true,sortOrder:2 },
  { slug:"starter-set",kind:"set",image:"/products/bundle.png",name:{ka:"საწყისი ნაკრები",en:"Starter bundle",ru:"Стартовый набор"},detail:{ka:"სტენდი და ბარათი ერთ კომპლექტში",en:"A stand and card in one set",ru:"Стенд и карта в одном наборе"},priceGel:35,compareAtPriceGel:59,stock:0,available:true,sortOrder:3 },
] as const;

export const plans = [
  {slug:"growth",name:{ka:"ReviewPortal",en:"ReviewPortal",ru:"ReviewPortal"},description:{ka:"ერთი ანგარიში. ყველა თქვენი ბიზნესი.",en:"One account. All your businesses.",ru:"Один аккаунт. Все ваши компании."},priceGel:50,compareAtPriceGel:undefined,features:{ka:["შეუზღუდავი ბიზნესი და ლოკაცია","საჩივრების მოგვარების პორტალები","დაბალი შეფასების პირადი უკუკავშირი","ანალიტიკის პანელი","QR და NFC ბმულები"],en:["Unlimited businesses & locations","Complaint-resolution portals","Private low-rating feedback","Analytics dashboard","QR and NFC-ready links"],ru:["Неограниченные компании и филиалы","Порталы для решения жалоб","Личная обратная связь при низкой оценке","Панель аналитики","Ссылки для QR и NFC"]},portalLimit:1000,visible:true,sortOrder:1},
  {slug:"business",name:{ka:"ბიზნესი",en:"Business",ru:"Бизнес"},description:{ka:"გუნდისა და მოცულობის მიხედვით შეთანხმებული პირობები.",en:"Terms tailored to your team and volume.",ru:"Условия под вашу команду и объём."},priceGel:0,compareAtPriceGel:undefined,features:{ka:["ყველა ფუნქცია","პრიორიტეტული ჩართვა","შეთანხმებული პირობები"],en:["Every platform feature","Priority onboarding","Custom terms"],ru:["Все функции платформы","Приоритетный запуск","Индивидуальные условия"]},portalLimit:1000,visible:true,sortOrder:2},
] as const;

export const whatsapp = (message: string) => `https://wa.me/995577665525?text=${encodeURIComponent(message)}`;
